encoding : UTF-8
title    : hashID
data_dir : data

orig_author : c0re@psypanda.org
orig_github : https://github.com/psypanda/hashID/

author      : mattwright324
github      : https://github.com/mattwright324/hashID/
gh_pages    : https://mattwright324.github.io/hashID/